name: GitHub Pages

on:
  release:
      types:
        - created
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
        - uses: actions/checkout@v2
      
        - name: Setup Node
          uses: actions/setup-node@v2.1.2
          with:
            node-version: '12.x'
          
        - name: Cache dependencies
          uses: actions/cache@v2
          with:
            path: ~/.npm
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-node-

        - run: npm ci
        - run: npm run zip

        - name: Chrome Addon Action
          # You may pin to the exact commit or the version.
          # uses: trmcnvn/chrome-addon@7fc5a5ad3ff597dc64d6a13de7dcaa8515328be7
          uses: trmcnvn/chrome-addon@v2
          with:
            # ID of the extension that you are updating
            extension: ${{ secrets.EXTENSION_ID }}
            # Path to a .zip of your addon
            zip: build/chrome-extension-template.zip
            # Google OAuth2 client id
            client-id: ${{ secrets.CLIENT_ID }}
            # Google OAuth2 client secret
            client-secret: ${{ secrets.CLIENT_SECRET }}
            # Google OAuth2 refresh token
            refresh-token: ${{ secrets.REFRESH_TOKEN }}
